4:
  url: 'http://creativecommons.org/licenses/by/2.0/'
  shortcut: 'cc-by'
  name: 'Createive Commons Attribution License'
5:
  url: "https://creativecommons.org/licenses/by-sa/2.0/"
  shortcut: 'cc-by-sa'
  name: 'Createive Commons Attribution-ShareAlike License'