-
  title: Clean your room
-
  title: Do some push-ups
-
  title: Learn words of a language
-
  title: Learn about a country
-
  title: Bring down the trash
-
  title: Bake a cake
-
  title: Waste some time
-
  title: Play an online game
-
  title: Call a friend